### ISSUE TITLE
Use in browser to support PWA

### ISSUE THREAD

**Issue by peterennis** [andygup/ionic2-esri-map#1] opened 2017-03-24 14:10 UTC
Instructions mention using the device but I am researching use across platforms.
Chrome looks like this. Is it planned to fix?
![capture036](https://cloud.githubusercontent.com/assets/140737/24297710/f54acd02-1060-11e7-9acc-2c074c56ea9c.png)

**Comment by andygup** [comment] 2017-03-24 15:50
@peterennis Thanks for the heads up, I'll have to investigate. If you have any suggestions in the meantime let me know.

**Comment by andygup** [comment] 2017-03-24 16:09
I've been unable to reproduce on Chrome  57.0.2987.110 (64-bit). Can you include a dump or screenshot of the developer console log?

**Comment by peterennis** [comment] 2017-03-25 15:52
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

This is on current Edge and shows the loop.
Not sure if the 404 is because I opened another browser tab.

![capture041](https://cloud.githubusercontent.com/assets/140737/24323786/4996c3fc-1138-11e7-8c85-96018269b6af.png)

**Comment by andygup** [comment] 2017-03-27 14:46
I don't have access to an Edge browser since I'm on a Mac. Maybe consider installing Chrome and seeing if it works okay?

The 404 errors and just Edge letting you know that a source map file is missing. This is related to debugging and is not supposed to affect how the application user interface is displayed.

**Comment by peterennis** [comment] 2017-03-28 03:55
Current Chrome.
![capture042](https://cloud.githubusercontent.com/assets/140737/24388436/8077be6e-132f-11e7-947a-54e8d9704792.png)

![capture043](https://cloud.githubusercontent.com/assets/140737/24388440/875f712c-132f-11e7-8080-94e376b7dc5a.png)

![capture044](https://cloud.githubusercontent.com/assets/140737/24388445/8dc7b7c2-132f-11e7-96d4-a75b6f844b9b.png)

**Comment by andygup** [comment] 2017-03-28 14:40
It looks like the [esri.css](https://github.com/andygup/ionic2-esri-map/blob/master/index.html#L39) isn't loading for some reason.

Here are some suggestions to try and find out what the deal is. There isn't anything I can do since I'm on a Mac. If you are able to dig into these it would be very helpful for anyone else that may have a similar issue:
* Make sure the [esri.css](https://github.com/andygup/ionic2-esri-map/blob/master/index.html#L39) is loading by using Chrome developers console Network tab.
* If it isn't loading then remove the [Content Security Policy](https://github.com/andygup/ionic2-esri-map/blob/master/index.html#L13-L37) block and retest. 
* Use the Chrome developers tools to select the map `div` on the page and then inspect the HTML and CSS. It should look roughly similar to this:

![image](https://cloud.githubusercontent.com/assets/510440/24411012/e9007004-1391-11e7-999c-d5b41a925ad8.png)

**Comment by peterennis** [comment] 2017-03-28 21:44
I will check on it tonight and report back.
If I run out of debug foo I will ping you for help.

**Comment by peterennis** [comment] 2017-03-29 04:29
Turns out the index.html file was bad. I copied it again and it looks good.
Snips from IE11, Edge, Chrome and Firefox:

![capture046](https://cloud.githubusercontent.com/assets/140737/24438587/2db05ffa-13fd-11e7-9f46-c4b9a24c9587.png)

![capture045](https://cloud.githubusercontent.com/assets/140737/24438580/2793c4f4-13fd-11e7-8a8b-7c07bee2fa75.png)

![capture047](https://cloud.githubusercontent.com/assets/140737/24438610/426fb788-13fd-11e7-9cba-1b2195a7a228.png)

![capture048](https://cloud.githubusercontent.com/assets/140737/24438612/486677d0-13fd-11e7-8ae0-b72d8166d0d1.png)

**Comment by peterennis** [comment] 2017-03-29 04:41
My next steps are to test integration with this:
https://github.com/Esri/terraformer-wkt-parser

**Comment by andygup** [comment] 2017-03-29 18:37
Awesome on both counts. Glad you got it working! I'm going to close this issue out.

**Closed as completed by andygup** 2017-03-29 18:37 UTC
